spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '  '
            client-secret: '  '
            redirect-uri: "https://www.mycom24data.p-e.kr/login/oauth2/code/google"
            scope:
              - email
              - profile
  servlet:
    session:
      persistent: true

server:
  port: 8081


